#!/usr/bin/env python3
"""
Run the full orthogonal KL selection pipeline with one command.

Pipeline:
1) generate_pool_nnt.py
2) build_rna_conflict_graphV2.py
3) select_from_conflict_graph.py
4) pool_rna_complement.py (complement file + orthogonality figure)

All outputs are written into a new folder:
  Orthogonal_RNA_Pool_<N>nt
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

DEFAULT_GUIDE = "CACGAAGUCAAUAC"


def _add_suffix_to_path(path: str, suffix: str) -> str:
    p = Path(path)
    if p.suffix:
        return str(p.with_name(f"{p.stem}{suffix}{p.suffix}"))
    return f"{path}{suffix}"


def _run(cmd: list[str], cwd: Path) -> None:
    print(f"\n[RUN] {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=str(cwd), check=True)


def _normalize_guides(raw_guides: list[str] | None) -> list[str]:
    if not raw_guides:
        return [DEFAULT_GUIDE]
    guides: list[str] = []
    for g in raw_guides:
        for part in g.replace(",", " ").split():
            if part.strip():
                guides.append(part.strip().upper())
    return guides or [DEFAULT_GUIDE]


def _print_user_instructions() -> None:
    print(
        """
Usage:
  python run_orthogonal_selection.py [options]

Options:
  -N, --num-nt   KL length N (default: 9)
  -R, --rounds   Number of randomized attempts in step 3 (default: 1000)
  -G, --guide    Guide sequence. Can be used multiple times.
                 Default guide: CACGAAGUCAAUAC
  -O, --output   Final output filename for step 4.
                 Default: Orthogonal_RNA_Pool_<N>nt.txt
  -U, --User     Show this instruction text.

Examples:
  python run_orthogonal_selection.py
  python run_orthogonal_selection.py -N 9 -R 2000
  python run_orthogonal_selection.py -G CACGAAGUCAAUAC -G GGGAAAUUU
  python run_orthogonal_selection.py -O MyFinalPool.txt

Output folder (auto-created):
  Orthogonal_RNA_Pool_<N>nt

Output files inside that folder:
  RNA_Pool_<N>nt.txt
  FilteredPool_<N>nt.txt
  ConflictGraph_<N>nt.txt
  SelectedPool_from_graph.txt
  Orthogonal_RNA_Pool_<N>nt.txt      (or filename from -O)
  orthogonality_<N>nt_RNA_Pool.png
""".strip()
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run orthogonal KL selection end-to-end.",
    )
    parser.add_argument("-N", "--num-nt", type=int, default=9, help="KL length N (default: 9).")
    parser.add_argument(
        "-R",
        "--rounds",
        type=int,
        default=1000,
        help="Number of randomized attempts in step 3 (default: 1000).",
    )
    parser.add_argument(
        "-G",
        "--guide",
        action="append",
        default=None,
        help=(
            "Guide sequence. Can be provided multiple times. "
            f"Default: {DEFAULT_GUIDE}"
        ),
    )
    parser.add_argument(
        "-O",
        "--output",
        type=str,
        default=None,
        help="Final output text filename for step 4.",
    )
    parser.add_argument(
        "-U",
        "--User",
        action="store_true",
        help="Show instruction of how to use this python file.",
    )
    return parser.parse_args()


def _replace_file(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(f"Expected file not found: {src}")
    if dst.exists():
        dst.unlink()
    src.replace(dst)


def main() -> None:
    args = parse_args()

    if args.User:
        _print_user_instructions()
        return

    if args.num_nt <= 0:
        raise ValueError("--num-nt must be positive.")
    if args.rounds <= 0:
        raise ValueError("--rounds must be positive.")

    guides = _normalize_guides(args.guide)

    script_dir = Path(__file__).resolve().parent
    functions_dir = script_dir / "functions"

    step1_script = functions_dir / "generate_pool_nnt.py"
    step2_script = functions_dir / "build_rna_conflict_graphV2.py"
    step3_script = functions_dir / "select_from_conflict_graph.py"
    step4_script = functions_dir / "pool_rna_complement.py"

    for sp in (step1_script, step2_script, step3_script, step4_script):
        if not sp.exists():
            raise FileNotFoundError(f"Required script not found: {sp}")

    out_dir = Path.cwd() / f"Orthogonal_RNA_Pool_{args.num_nt}nt"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Final filenames requested by user.
    step1_final = f"RNA_Pool_{args.num_nt}nt.txt"
    step2_filtered_final = f"FilteredPool_{args.num_nt}nt.txt"
    step2_graph_final = f"ConflictGraph_{args.num_nt}nt.txt"
    step3_selected_final = "SelectedPool_from_graph.txt"
    step4_final = Path(args.output).name if args.output else f"Orthogonal_RNA_Pool_{args.num_nt}nt.txt"
    step4_figure = f"orthogonality_{args.num_nt}nt_RNA_Pool.png"

    # Intermediate names generated by existing scripts (they append '_out').
    step2_filtered_tmp = _add_suffix_to_path(step2_filtered_final, "_out")
    step2_graph_tmp = _add_suffix_to_path(step2_graph_final, "_out")
    step3_selected_tmp = _add_suffix_to_path(step3_selected_final, "_out")
    step4_tmp = _add_suffix_to_path(step3_selected_tmp, "_complement")

    print("=== Orthogonal KL Selection Pipeline ===", flush=True)
    print(f"Output folder: {out_dir}", flush=True)
    print(f"N: {args.num_nt}", flush=True)
    print(f"Rounds: {args.rounds}", flush=True)
    print(f"Guides: {', '.join(guides)}", flush=True)

    # Step 1
    cmd1 = [
        sys.executable,
        str(step1_script),
        str(args.num_nt),
        "--output",
        step1_final,
    ]
    _run(cmd1, out_dir)

    # Step 2
    cmd2 = [
        sys.executable,
        str(step2_script),
        "--num-nt",
        str(args.num_nt),
        "--input",
        step1_final,
        "--seq-out",
        step2_filtered_final,
        "--graph-out",
        step2_graph_final,
    ]
    for g in guides:
        cmd2.extend(["--guide", g])
    _run(cmd2, out_dir)

    # Step 3
    cmd3 = [
        sys.executable,
        str(step3_script),
        "--seq-file",
        step2_filtered_tmp,
        "--graph-file",
        step2_graph_tmp,
        "--rounds",
        str(args.rounds),
        "--output",
        step3_selected_final,
    ]
    _run(cmd3, out_dir)

    # Step 4
    cmd4 = [
        sys.executable,
        str(step4_script),
        step3_selected_tmp,
        "--output-figure",
        step4_figure,
    ]
    _run(cmd4, out_dir)

    # Rename intermediate '_out' files to requested final names.
    _replace_file(out_dir / step2_filtered_tmp, out_dir / step2_filtered_final)
    _replace_file(out_dir / step2_graph_tmp, out_dir / step2_graph_final)
    _replace_file(out_dir / step3_selected_tmp, out_dir / step3_selected_final)
    _replace_file(out_dir / step4_tmp, out_dir / step4_final)
    print("\n=== Done ===", flush=True)
    print(f"Generated files in: {out_dir}", flush=True)
    print(f"- {step1_final}", flush=True)
    print(f"- {step2_filtered_final}", flush=True)
    print(f"- {step2_graph_final}", flush=True)
    print(f"- {step3_selected_final}", flush=True)
    print(f"- {step4_final}", flush=True)
    print(f"- {step4_figure}", flush=True)


if __name__ == "__main__":
    main()
