from __future__ import annotations

import argparse
from pathlib import Path

from .nupack_runner import run_nupack_design


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run NUPACK sequence design for tile blocks generated by the GUI."
    )
    parser.add_argument(
        "input_file",
        help="Input tile sequence file (e.g., <prefix>_generated_sequence.txt).",
    )
    parser.add_argument(
        "-o",
        "--output-file",
        default="",
        help="Output file path. Default: <input_stem>_nupack_output.txt in the same directory.",
    )
    parser.add_argument(
        "--trials",
        type=int,
        default=3,
        help="Number of NUPACK design trials per tile (default: 3).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for NUPACK design options (default: 42).",
    )
    parser.add_argument(
        "--f-stop",
        type=float,
        default=0.02,
        help="NUPACK DesignOptions f_stop value (default: 0.02).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    in_path = Path(args.input_file).resolve()
    if not in_path.exists():
        print(f"Input file not found: {in_path}")
        return 1

    if args.output_file:
        out_path = Path(args.output_file).resolve()
    else:
        out_path = in_path.with_name(in_path.stem + "_nupack_output.txt")

    result = run_nupack_design(
        input_file=in_path,
        output_file=out_path,
        trials=args.trials,
        seed=args.seed,
        f_stop=args.f_stop,
    )

    print(f"Output: {result.output_path}")
    print(
        f"Tiles: {result.total_tiles} | "
        f"Succeeded: {result.success_tiles} | Failed: {result.failed_tiles}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())

